version: '2'
services:
  onlyoffice-documentserver:
    build:
      context: .
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      #- JWT_ENABLED=true
      #- JWT_SECRET=secret
      #- JWT_HEADER=Authorization
      #- JWT_IN_BODY=true
    ports:
      - '4000:80'
      - '4443:443'
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - data:/var/www/onlyoffice/Data
       - logs:/var/log/onlyoffice
       - cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
       - example:/var/www/onlyoffice/documentserver-example/public/files
       - fonts:/usr/share/fonts/truetype/custom
       - redis:/var/lib/redis
       
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - postgresql:/var/lib/postgresql

volumes:
  postgresql:
  rabbitmq:
  data:
  logs:
  cache:
  example:
  fonts:
  redis:
